---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 1024

## The forwarded_port port feature lets you connect to ports on the VM guest via
## localhost on the host.
## see also: https://docs.vagrantup.com/v2/networking/forwarded_ports.html

  network:
    - ["forwarded_port", {guest: 9000, host: 8088}]

provisioner:
  name: chef_zero

## require_chef_omnibus specifies a specific chef version to install. You can
## also set this to `true` to always use the latest version.
## see also: https://docs.chef.io/config_yml_kitchen.html

#  require_chef_omnibus: 12.5.0

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04

suites:
  - name: default
    run_list:
        - recipe[kafka-manager_wrapper]
    attributes:
