name             'elasticsearch_wrapper'
maintainer       'Max2 Inc'
maintainer_email 'shubhanshu@max2.com'
license          'All rights reserved'
description      'Installs/Configures elasticsearch_wrapper'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'poise','>=0.0.0'
depends          'elasticsearch','>=1.0.0'
depends          'apt', '>=2.9.2'
depends          'java', '~> 1.36.0'
