name             'flume_wrapper'
maintainer       'YOUR_COMPANY_NAME'
maintainer_email 'YOUR_EMAIL'
license          'All rights reserved'
description      'Installs/Configures flume_wrapper'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.30'
depends          'flume_agent'
depends          'deploy_key'
depends          'maven'
depends          'apt'
depends          'java'
