---
driver:
  name: vagrant
  requrie_chef_omnibus: true
  customize:
    memory: 2048
    cpus: 2
  network:
    - ["private_network", {type: "dhcp"}]

provisioner:
  name: chef_zero
  client_rb:
    audit_mode: :enabled

platforms:
  - name: ubuntu-master
    driver:
      box: opscode-ubuntu-14.04
    run_list:
      - recipe[sensu_wrapper::master]
  - name: ubuntu-client
    driver:
      box: opscode-ubuntu-14.04
    run_list:
      - recipe[sensu_wrapper::default]

suites:
  - name: default
