name 'schema_repo_wrapper'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures schema_repo_wrapper'
long_description 'Installs/Configures schema_repo_wrapper'
version '0.3.0'

 depends 'java', '~> 1.36.0'
 depends 'ark', '~> 0.9.0'
 depends 'apt', '~> 2.9.2'
