---
driver:
  name: vagrant
  require_chef_omnibus: true
  customize:
    memory: 1024

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    driver:
      box: opscode-ubuntu-14.04

suites:
  - name: nginx-oracle
    run_list:
      - recipe[nginx_wrapper::service]
    attributes:
